// Mocks generated by Mockito 5.1.0 from annotations
// in bicycle_trip_planner/test/managers/location_manager_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:bicycle_trip_planner/models/locator.dart' as _i8;
import 'package:geolocator/geolocator.dart' as _i3;
import 'package:google_maps_flutter/google_maps_flutter.dart' as _i4;
import 'package:location/location.dart' as _i5;
import 'package:location_platform_interface/location_platform_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeLocationData_0 extends _i1.Fake implements _i2.LocationData {}

class _FakeGeolocator_1 extends _i1.Fake implements _i3.Geolocator {}

class _FakeLatLng_2 extends _i1.Fake implements _i4.LatLng {}

/// A class which mocks [Location].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocation extends _i1.Mock implements _i5.Location {
  MockLocation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i2.LocationData> get onLocationChanged =>
      (super.noSuchMethod(Invocation.getter(#onLocationChanged),
              returnValue: Stream<_i2.LocationData>.empty())
          as _i6.Stream<_i2.LocationData>);
  @override
  _i6.Future<bool> changeSettings(
          {_i2.LocationAccuracy? accuracy = _i2.LocationAccuracy.high,
          int? interval = 1000,
          double? distanceFilter = 0.0}) =>
      (super.noSuchMethod(
          Invocation.method(#changeSettings, [], {
            #accuracy: accuracy,
            #interval: interval,
            #distanceFilter: distanceFilter
          }),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  _i6.Future<bool> isBackgroundModeEnabled() =>
      (super.noSuchMethod(Invocation.method(#isBackgroundModeEnabled, []),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  _i6.Future<bool> enableBackgroundMode({bool? enable = true}) =>
      (super.noSuchMethod(
          Invocation.method(#enableBackgroundMode, [], {#enable: enable}),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  _i6.Future<_i2.LocationData> getLocation() => (super.noSuchMethod(
          Invocation.method(#getLocation, []),
          returnValue: Future<_i2.LocationData>.value(_FakeLocationData_0()))
      as _i6.Future<_i2.LocationData>);
  @override
  _i6.Future<_i2.PermissionStatus> hasPermission() => (super.noSuchMethod(
          Invocation.method(#hasPermission, []),
          returnValue:
              Future<_i2.PermissionStatus>.value(_i2.PermissionStatus.granted))
      as _i6.Future<_i2.PermissionStatus>);
  @override
  _i6.Future<_i2.PermissionStatus> requestPermission() => (super.noSuchMethod(
          Invocation.method(#requestPermission, []),
          returnValue:
              Future<_i2.PermissionStatus>.value(_i2.PermissionStatus.granted))
      as _i6.Future<_i2.PermissionStatus>);
  @override
  _i6.Future<bool> serviceEnabled() =>
      (super.noSuchMethod(Invocation.method(#serviceEnabled, []),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  _i6.Future<bool> requestService() =>
      (super.noSuchMethod(Invocation.method(#requestService, []),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
  @override
  _i6.Future<_i2.AndroidNotificationData?> changeNotificationOptions(
          {String? channelName,
          String? title,
          String? iconName,
          String? subtitle,
          String? description,
          _i7.Color? color,
          bool? onTapBringToFront}) =>
      (super.noSuchMethod(
              Invocation.method(#changeNotificationOptions, [], {
                #channelName: channelName,
                #title: title,
                #iconName: iconName,
                #subtitle: subtitle,
                #description: description,
                #color: color,
                #onTapBringToFront: onTapBringToFront
              }),
              returnValue: Future<_i2.AndroidNotificationData?>.value())
          as _i6.Future<_i2.AndroidNotificationData?>);
}

/// A class which mocks [Locator].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocator extends _i1.Mock implements _i8.Locator {
  MockLocator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set settings(_i3.LocationSettings? _settings) =>
      super.noSuchMethod(Invocation.setter(#settings, _settings),
          returnValueForMissingStub: null);
  @override
  _i3.LocationAccuracy get accuracy =>
      (super.noSuchMethod(Invocation.getter(#accuracy),
          returnValue: _i3.LocationAccuracy.lowest) as _i3.LocationAccuracy);
  @override
  set accuracy(_i3.LocationAccuracy? _accuracy) =>
      super.noSuchMethod(Invocation.setter(#accuracy, _accuracy),
          returnValueForMissingStub: null);
  @override
  int get distanceFilter =>
      (super.noSuchMethod(Invocation.getter(#distanceFilter), returnValue: 0)
          as int);
  @override
  set distanceFilter(int? _distanceFilter) =>
      super.noSuchMethod(Invocation.setter(#distanceFilter, _distanceFilter),
          returnValueForMissingStub: null);
  @override
  _i3.Geolocator get geolocator =>
      (super.noSuchMethod(Invocation.getter(#geolocator),
          returnValue: _FakeGeolocator_1()) as _i3.Geolocator);
  @override
  set geolocator(_i3.Geolocator? _geolocator) =>
      super.noSuchMethod(Invocation.setter(#geolocator, _geolocator),
          returnValueForMissingStub: null);
  @override
  _i6.Future<_i4.LatLng> locate() =>
      (super.noSuchMethod(Invocation.method(#locate, []),
              returnValue: Future<_i4.LatLng>.value(_FakeLatLng_2()))
          as _i6.Future<_i4.LatLng>);
}
