// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKu0ZcxGEoMgD-sTLmHMML1OoVpvKu8AQ',
    appId: '1:407783421630:web:607759082708b3425a10ef',
    messagingSenderId: '407783421630',
    projectId: 'bicycletripplanner-c1288',
    authDomain: 'bicycletripplanner-c1288.firebaseapp.com',
    storageBucket: 'bicycletripplanner-c1288.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgvw8h5qbGO3N5ze7j-OzlZE2OE_szzfo',
    appId: '1:407783421630:android:1f98a4f09066a1f65a10ef',
    messagingSenderId: '407783421630',
    projectId: 'bicycletripplanner-c1288',
    storageBucket: 'bicycletripplanner-c1288.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJJZC8AV3FneriFTDsRMFna4ARgCU2ZS0',
    appId: '1:407783421630:ios:3ea0a2953edde0745a10ef',
    messagingSenderId: '407783421630',
    projectId: 'bicycletripplanner-c1288',
    storageBucket: 'bicycletripplanner-c1288.appspot.com',
    iosClientId: '407783421630-qupl3vj243qldd31che4uaj56qmd67c6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bicycleTripPlanner',
  );
}
